apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-instance
  labels:
    app: chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: poc_chatbot:1.0.0
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  labels:
    app: chatbot
spec:
  selector:
    app: chatbot
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: 8501